apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lokie-stack
spec:
  destination:
    name: ''
    namespace: loki-ns
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/loki-stack
    repoURL: 'https://github.com/raghuveer125/loki-stack.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true